### ISSUE TITLE
How to obtain the corresponding caption of the image in NSD from COCO dataset?

### ISSUE THREAD

**Issue by xiaominli1020** [weihaox/BrainHub#1]
Hi, thanks for your nice work.

I am not sure how to obtain the captions for images in NSD.

And you mentioned in readme "We provide the processed [text](https://github.com/weihaox/brainhub/caption) and [boundingbox](https://github.com/weihaox/brainhub/bbox) groundtruth."

but I cannot find the processed text and ground truth.

**Comment by weihaox** [comment]
The COCO caption data is provided in [fmri_cococap.json](https://github.com/weihaox/BrainHub/blob/main/caption/fmri_cococap.json) (this is for testing only, as we do not need groundtruth captions for training). If you want to extract captions yourself, you will need the `nsd_stim_info_merged.csv` (which contains the correspondences of COCO IDs and NSD IDs), as well as `captions_train2017.json` and `captions_val2017.json`.
