### ISSUE TITLE
What is the key of the results

### ISSUE THREAD

**Issue by Boltzmachine** [weihaox/BrainHub#2]
for example,
https://github.com/weihaox/BrainHub/blob/main/caption/comparison/umbrae/sub01_decoded_caption.json

Do the keys like "0", "1" corresponds to the image indinces of MindEye?

**Comment by weihaox** [comment]
Yes, the indices are the same when using data provided by MindEye. Please note that the indices will be different if downloading data from NSD as in [SDRecon](https://github.com/yu-takagi/StableDiffusionReconstruction) or [Braindiffuser](https://github.com/ozcelikfu/brain-diffuser).
