### ISSUE TITLE
Questions about RoI

### ISSUE THREAD

**Issue by xiaoyao3302** [weihaox/BrainHub#4]
Hi, thanks for the wonderful work! It really inspired me a lot.
I  have some tiny issues with the fMRI signal. I wonder if we can get the precise RoI for each voxel, as shown in Table 2 of the supplements.  I wonder if we can know which region a certain voxel lies, like V1 or V2? (How can we visualize it?)
I would be more than grateful for your help!
Thanks again for your attention!

**Comment by weihaox** [comment]
Hi @xiaoyao3302 

The official NSD doc provides such info. Data preprocessing scripts from [SDRecon](https://github.com/yu-takagi/StableDiffusionReconstruction/blob/main/codes/utils/make_subjmri.py) and [Brain-Diffuser](https://github.com/ozcelikfu/brain-diffuser/blob/main/scripts/roi_extract.py) handle ROI processing for specific voxels. For visualization, [pycortex](https://gallantlab.org/pycortex/) may be useful, though I haven’t personally used it. Hope this helps!

**Comment by xiaoyao3302** [comment]
Many thanks for the quick and useful response, I will check the links! Thank you! Congratulations again for the wonderful work!
